AccessKey = "AKIAJI4ZI2LLZEM6HXLQ"
AccessSecret = "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"
Region = "ap-northeast-1"
DownloadRootDir = "D:\\Users\\ryan.zhu\\share-dev\\out\\aws\\s3"
[[DownloadFiles]]
    Bucket = "mzh-everonet-test-bucket"
    FilePatterns = [
        "fil/ins/00000013/in/20101113/00000013_20101113_[\\d]{8}$"
    ]
    FilePaths = [
        "fil/ins/00000013/in/20101113/00000013_20101113_20101117"
    ]
    DownloadDir = "20210427"